# Generated by Django 5.2.6 on 2025-10-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_student_photo_alter_student_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='student_app.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/'),
        ),
    ]
